name: CI Workflow

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t rememory-docker-test .
          docker tag rememory-docker-test nahyeonn/rememory-docker-test:latest
          docker push nahyeonn/rememory-docker-test:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: prev sha get test
        run: echo ${GITHUB_REF}

      - name: Pull Docker image
        run: |
          sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          sudo docker pull nahyeonn/rememory-docker-test:latest

      - name: Delete Old docker container
        run: |
          sudo docker rm -f container || true
      # - name: Create .env file
      #   run: echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --env-file .env --name container nahyeonn/rememory-docker-test:latest
